/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jackrabbit.oak.segment.consensus;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;
import java.util.UUID;

/**
 * Represents a proposal to write segments to the global distributed store.
 * <p>
 * Part of the Blockchain AEM consensus protocol. Proposals are created by
 * participants who wish to publish content to the global {@code /oak-chain}
 * mount point.
 * <p>
 * Each proposal contains:
 * <ul>
 *   <li>Unique proposal ID</li>
 *   <li>Wallet UUID (content owner)</li>
 *   <li>Target content path (must be within {@code /oak-chain/content/<wallet-uuid>})</li>
 *   <li>Segment IDs to be written</li>
 *   <li>Payment verification proof (EVM transaction hash)</li>
 *   <li>Cryptographic signature</li>
 * </ul>
 *
 * @see Validator
 * @see Vote
 * @see ConsensusEngine
 */
public interface Proposal {

    /**
     * Returns the unique identifier for this proposal.
     * <p>
     * Generated by the proposer and used to track the proposal through
     * the consensus process.
     *
     * @return the proposal ID
     */
    @NotNull
    UUID getProposalId();

    /**
     * Returns the wallet UUID of the content owner.
     * <p>
     * This wallet must own the target content path. The wallet is derived
     * from the public key used to sign this proposal.
     *
     * @return the wallet UUID
     */
    @NotNull
    UUID getWalletId();

    /**
     * Returns the JCR path where content will be written.
     * <p>
     * Must be within the namespace {@code /oak-chain/content/<wallet-uuid>/*}.
     * The consensus engine will reject proposals that violate this constraint.
     *
     * @return the target path
     */
    @NotNull
    String getTargetPath();

    /**
     * Returns the list of segment IDs to be written.
     * <p>
     * These segments must already exist in the proposer's local segment store
     * and will be transferred to the global store upon consensus approval.
     *
     * @return list of segment IDs (as UUIDs)
     */
    @NotNull
    List<UUID> getSegmentIds();

    /**
     * Returns the payment verification proof.
     * <p>
     * This is typically an Ethereum transaction hash proving that the proposer
     * paid the required tokens to the payment verifier smart contract.
     *
     * @return EVM transaction hash (e.g., "0x123abc...")
     */
    @NotNull
    String getPaymentProof();

    /**
     * Returns the timestamp when this proposal was created (Unix epoch milliseconds).
     *
     * @return creation timestamp
     */
    long getTimestamp();

    /**
     * Returns the cryptographic signature of this proposal.
     * <p>
     * The signature is computed over the proposal contents using the wallet's
     * private key (ECDSA). Validators will verify this signature using the
     * public key associated with the wallet UUID.
     *
     * @return the signature bytes
     */
    @NotNull
    byte[] getSignature();

    /**
     * Returns the estimated storage cost in bytes.
     * <p>
     * Used by validators to verify that the payment amount is sufficient.
     *
     * @return estimated byte size
     */
    long getEstimatedSize();

    /**
     * Returns optional binary reference URIs if this proposal includes large assets.
     * <p>
     * In the BYOD (Bring Your Own DataStore) model, large binaries are stored
     * in the participant's own datastore. This field contains the URIs where
     * those binaries can be accessed.
     *
     * @return list of binary URIs, or empty list if none
     */
    @NotNull
    List<String> getBinaryUris();

    /**
     * Returns the protocol version of this proposal.
     * <p>
     * Allows for future protocol evolution while maintaining backward compatibility.
     *
     * @return protocol version (e.g., "1.0")
     */
    @NotNull
    String getProtocolVersion();

    /**
     * Validates this proposal's structure and constraints.
     * <p>
     * Checks:
     * <ul>
     *   <li>Target path is within wallet namespace</li>
     *   <li>Signature is valid</li>
     *   <li>All required fields are present</li>
     *   <li>Segment list is not empty</li>
     * </ul>
     *
     * @return null if valid, otherwise an error message
     */
    @Nullable
    String validate();
}

