/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jackrabbit.oak.spi.security.authentication.web3;

import org.apache.jackrabbit.oak.spi.security.authentication.credentials.AbstractCredentials;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

/**
 * Credentials containing a biometric signature (P-256/secp256r1) for Web3 wallet authentication.
 * 
 * <p>These credentials are typically created by a front-end application after prompting the user
 * for biometric authentication (Face ID, Touch ID, Windows Hello) via WebAuthn/FIDO2. The
 * resulting signature is verified against either:</p>
 * <ul>
 *   <li><strong>Local verification</strong>: JVM's EC crypto verifies P-256 signature</li>
 *   <li><strong>On-chain verification</strong>: EIP-7951 precompile verifies via Ethereum smart contract</li>
 * </ul>
 * 
 * <h2>Usage Example (Front-End)</h2>
 * <pre>
 * // 1. User triggers biometric prompt in browser
 * const assertion = await navigator.credentials.get({
 *   publicKey: { challenge, allowCredentials: [...] }
 * });
 * 
 * // 2. Convert to Web3BiometricCredentials format
 * const credentials = {
 *   credentialId: assertion.id,
 *   signature: base64(assertion.response.signature),
 *   publicKey: base64(assertion.response.publicKey),
 *   challenge: base64(challenge),
 *   walletAddress: "0x1234..."
 * };
 * 
 * // 3. Send to Oak repository login
 * POST /repository/login
 * Body: { credentials }
 * </pre>
 * 
 * <h2>Usage Example (Java)</h2>
 * <pre>
 * Repository repo = ...;
 * Web3BiometricCredentials creds = new Web3BiometricCredentials(
 *     "credential-id-from-webauthn",
 *     signatureBytes,
 *     publicKeyBytes,
 *     challengeBytes,
 *     "0x1234567890abcdef1234567890abcdef12345678"
 * );
 * Session session = repo.login(creds, "default");
 * // Now authenticated with wallet address as principal
 * </pre>
 * 
 * @see Web3BiometricLoginModule
 * @see Web3Principal
 */
public final class Web3BiometricCredentials extends AbstractCredentials {
    
    /**
     * WebAuthn credential ID (passkey identifier).
     * Example: "AQIDBAUGBwg..." (base64-encoded bytes from WebAuthn)
     */
    private final String credentialId;
    
    /**
     * P-256 (secp256r1) signature over challenge.
     * Format: DER-encoded ECDSA signature (r, s values)
     */
    private final byte[] signature;
    
    /**
     * P-256 public key (65 bytes: 0x04 prefix + x coordinate + y coordinate).
     * Example: 04<32 bytes x><32 bytes y>
     */
    private final byte[] publicKey;
    
    /**
     * Challenge/nonce that was signed (prevents replay attacks).
     * Typically 32 random bytes generated by server.
     */
    private final byte[] challenge;
    
    /**
     * Ethereum wallet address associated with this passkey.
     * Format: 0x-prefixed 40 hex characters (checksummed per EIP-55)
     */
    private final String walletAddress;
    
    /**
     * Creates new Web3 biometric credentials.
     * 
     * @param credentialId WebAuthn credential identifier
     * @param signature P-256 signature bytes (DER-encoded ECDSA)
     * @param publicKey P-256 public key bytes (65 bytes: 0x04 + x + y)
     * @param challenge Challenge bytes that were signed
     * @param walletAddress Ethereum wallet address (0x-prefixed)
     * @throws NullPointerException if any parameter is null
     * @throws IllegalArgumentException if wallet address format is invalid
     */
    public Web3BiometricCredentials(
            @NotNull String credentialId,
            @NotNull byte[] signature,
            @NotNull byte[] publicKey,
            @NotNull byte[] challenge,
            @NotNull String walletAddress) {
        
        super(walletAddress); // userId = walletAddress
        
        this.credentialId = Objects.requireNonNull(credentialId, "Credential ID cannot be null");
        this.signature = Objects.requireNonNull(signature, "Signature cannot be null").clone();
        this.publicKey = Objects.requireNonNull(publicKey, "Public key cannot be null").clone();
        this.challenge = Objects.requireNonNull(challenge, "Challenge cannot be null").clone();
        this.walletAddress = Objects.requireNonNull(walletAddress, "Wallet address cannot be null");
        
        // Validate wallet address format (basic check)
        if (!walletAddress.matches("^0x[0-9a-fA-F]{40}$")) {
            throw new IllegalArgumentException("Invalid Ethereum address format: " + walletAddress);
        }
    }
    
    /**
     * Returns the WebAuthn credential ID.
     * 
     * @return credential ID string
     */
    @NotNull
    public String getCredentialId() {
        return credentialId;
    }
    
    /**
     * Returns a copy of the P-256 signature bytes.
     * 
     * @return signature bytes (DER-encoded ECDSA)
     */
    @NotNull
    public byte[] getSignature() {
        return signature.clone();
    }
    
    /**
     * Returns a copy of the P-256 public key bytes.
     * 
     * @return public key bytes (65 bytes: 0x04 prefix + x + y)
     */
    @NotNull
    public byte[] getPublicKey() {
        return publicKey.clone();
    }
    
    /**
     * Returns a copy of the challenge bytes.
     * 
     * @return challenge bytes that were signed
     */
    @NotNull
    public byte[] getChallenge() {
        return challenge.clone();
    }
    
    /**
     * Returns the Ethereum wallet address.
     * 
     * @return wallet address (0x-prefixed, 42 characters)
     */
    @NotNull
    public String getWalletAddress() {
        return walletAddress;
    }
    
    /**
     * Returns the wallet address (same as {@link #getWalletAddress()}).
     * Overrides {@link AbstractCredentials#getUserId()} to use wallet as user ID.
     * 
     * @return wallet address
     */
    @Override
    @NotNull
    public String getUserId() {
        return walletAddress;
    }
    
    /**
     * Two credentials are equal if all fields match.
     * 
     * @param obj object to compare
     * @return true if equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Web3BiometricCredentials)) {
            return false;
        }
        Web3BiometricCredentials other = (Web3BiometricCredentials) obj;
        return credentialId.equals(other.credentialId) &&
               Arrays.equals(signature, other.signature) &&
               Arrays.equals(publicKey, other.publicKey) &&
               Arrays.equals(challenge, other.challenge) &&
               walletAddress.equalsIgnoreCase(other.walletAddress); // Case-insensitive per Ethereum
    }
    
    /**
     * Hash code based on credential ID and wallet address.
     * 
     * @return hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(credentialId, walletAddress.toLowerCase());
    }
    
    /**
     * String representation for debugging (excludes sensitive signature data).
     * 
     * @return string like "Web3BiometricCredentials[wallet=0x1234..., credentialId=...]"
     */
    @Override
    public String toString() {
        return "Web3BiometricCredentials[" +
               "wallet=" + walletAddress +
               ", credentialId=" + credentialId +
               ", signatureLen=" + signature.length +
               ", publicKeyLen=" + publicKey.length +
               ", challengeLen=" + challenge.length +
               "]";
    }
}

